#ifndef header_h
#define header_h

String file1=
"<!DOCTYPE html>\r\n"
"<head>\r\n"
"<title>WifiSmartControl</title>\r\n"
"<script type=\"text/javascript\">\r\n"
"window.onload=Pinstatus;\r\n"
"function Pinstatus(){\r\n"
"morestatus();\r\n"
"}\r\n"
"function morestatus(){\r\n"
"setTimeout(morestatus, 4000);\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Status\";\r\n"
"server = \"status/99\";\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasyncstatus;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send();\r\n"
"}\r\n"
"function updateasyncstatus(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"fullset = result.split(\"#\");\r\n"
"document.getElementById(\"description\").innerHTML = fullset;\r\n"
"for(i = 1; i < fullset.length; i++){\r\n"
"PinPair = fullset[i];\r\n"
"singleset = PinPair.split(\"=\");\r\n"
"PN = singleset[0];\r\n"
"Pinstatus = singleset[1];\r\n"
"if (PN > 11)\r\n"
"{\r\n"
"ActNum = \"action\" + PN;\r\n"
"TxtNum = \"text\" + PN;\r\n"
"if (Pinstatus == 0)\r\n"
"{\r\n"
"PinAct = \"1\";\r\n"
"text = \"Off\";\r\n"
"}\r\n"
"else\r\n"
"{\r\n"
"PinAct = \"0\";\r\n"
"text = \"On\";\r\n"
"}\r\n"
"document.getElementById(ActNum).value = PinAct;\r\n"
"document.getElementById(TxtNum).innerHTML = text;\r\n"
"}\r\n"
"if (PN == 4)\r\n"
"{\r\n"
"TxtNum = \"text\" + PN;\r\n"
"if (Pinstatus == 1)\r\n"
"{\r\n"
"text = \"On\";\r\n"
"}\r\n"
"else\r\n"
"{\r\n"
"text = \"Off\";\r\n"
"}\r\n"
"document.getElementById(TxtNum).innerHTML = text;\r\n"
"}\r\n"
"if (PN == 5 )\r\n"
"{\r\n"
"PinVal = parseInt(singleset[1]);\r\n"
"DacNum = \"dac\" + PN;\r\n"
"ValNum = \"valueDac\" + PN;\r\n"
"document.getElementById(DacNum).value = PinVal;\r\n"
"document.getElementById(ValNum).innerHTML = PinVal;\r\n"
"}\r\n"
"if (PN.substr(0,1) == \"A\")\r\n"
"{\r\n"
"PinVal = parseFloat(singleset[1]);\r\n"
"AnalogNum = \"analog\" + PN.substr(1,2);\r\n"
"document.getElementById(AnalogNum).value = PinVal;\r\n"
"}\r\n"
"}\r\n"
"}\r\n"
"}\r\n"
"function sendbutton(Pin,action){\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Button Click\";\r\n"
"server = \"digital/\" + Pin + \"/\" + action;\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasyncbutton;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send(null);\r\n"
"}\r\n"

"function updateasyncbutton(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"singleset = result.split(\",\");\r\n"
"PinType = singleset[0];\r\n"
"PinNum = singleset[1];\r\n"
"Pinstatus = singleset[2];\r\n"
"ActNum = \"action\" + PinNum;\r\n"
"TxtNum = \"text\" + PinNum;\r\n"
"if (Pinstatus == 0)\r\n"
"{\r\n"
"PinAct = \"1\";\r\n"
"text = \"Off\";\r\n"
"}\r\n"
"else\r\n"
"{\r\n"
"PinAct = \"0\";\r\n"
"text = \"On\";\r\n"
"}\r\n"
"document.getElementById(ActNum).value = PinAct;\r\n"
"document.getElementById(TxtNum).innerHTML = text;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"}\r\n"
"}\r\n"

"function sendDac(Pin,value){\r\n"
"ValNum = \"valueDac\" + Pin;\r\n"
"document.getElementById(ValNum).innerHTML=value;\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Slider\";\r\n"
"server = \"dac/\" + Pin + \"/\" + value;\r\n"
"request = new XMLHttpRequest();\r\n"
"request.onreadystatechange = updateasyncDac;\r\n"
"request.open(\"GET\", server, true);\r\n"
"request.send(null);\r\n"
"}\r\n"

"function updateasyncDac(){\r\n"
"if ((request.readyState == 4) && (request.status == 200))\r\n"
"{\r\n"
"result = request.responseText;\r\n"
"singleset = result.split(\",\");\r\n"
"PinType = singleset[0];\r\n"
"PinNum = singleset[1];\r\n"
"PinVal = parseInt(singleset[2]);\r\n"
"DacNum = \"dac\" + PinNum;\r\n"
"ValNum = \"valueDac\" + PinNum;\r\n"
"document.getElementById(DacNum).value = PinVal;\r\n"
"document.getElementById(ValNum).innerHTML = PinVal;\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"}\r\n"
"}\r\n"


"</script>\r\n"
"</head>\r\n"
"<font face=\"Arial\">\r\n"
"<table name=\"Table\" border=\"3\" cellpadding=\"6\">\r\n"
"<br>\r\n"
"</td>\r\n"
"</tr>\r\n"
"<tr> <td align=\"center\" colspan=\"1\" >Digital Input</td> \r\n" 
"<td align=\"center\" colspan=\"1\" >PWM Output</td> \r\n" 
"<td align=\"center\" colspan=\"6\" >Digital Output</td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td align=\"center\">\r\n"
"GPIO 4\r\n"
"<br>\r\n"
"<p id=\"text4\">Off</p>\r\n"
"</td>\r\n"

"<td align=\"center\">\r\n"
"GPIO 15\r\n"
" <br>\r\n"
"<input type=\"hidden\" name=\"pin\" value=\"15\" id=\"pin15\" />\r\n"
"<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac0\" min=\"0\" max=\"1024\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin15').value,\r\n"
"this.value);\"/>\r\n"
"<br>\r\n"
"<span id=\"valueDac15\">0</span>\r\n"
"</td>\r\n"

"<td align=\"center\">\r\n"
"<input type=\"hidden\" name=\"pin\" value=\"12\" id=\"pin12\" />\r\n"
"<input type=\"hidden\" name=\"action\" value=\"0\" id=\"action12\" />\r\n"
"<button onclick=\"sendbutton(document.getElementById('pin12').value,document.getElementById('action12').value);\"/>GPIO 12</button>\r\n"
"<p id=\"text12\">Off</p>"
"</td>\r\n"

"<td align=\"center\">\r\n"
"<input type=\"hidden\" name=\"pin\" value=\"13\" id=\"pin13\" />\r\n"
"<input type=\"hidden\" name=\"action\" value=\"0\" id=\"action13\" />\r\n"
"<button onclick=\"sendbutton(document.getElementById('pin13').value,document.getElementById('action13').value);\"/>GPIO 13</button>\r\n"
"<p id=\"text13\">Off</p>"
"</td>\r\n"
"</tr>\r\n"

"</table>\r\n"

"<p id=\"description\"> - </p>\r\n"
"</font>\r\n"
"</html>\r\n";

#endif
